language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build ./DockerCliWrapper.sln --configuration Release
  - dotnet test ./DockerCliWrapper.Tests/bin/Release/netcoreapp2.0/DockerCliWrapper.Tests.dll