namespace DockerCliWrapper.Docker.Container
{
    public enum ContainerEventStatus
    {
        Unknown,
        Attach,
        Commit,
        Copy,
        Create,
        Destroy,
        Detach,
        Die,
        ExecCreate,
        ExecDetach,
        ExecStart,
        Export,
        HealthStatus,
        Kill,
        Oom,
        Pause,
        Rename,
        Resize,
        Restart,
        Start,
        Stop,
        Top,
        Unpause,
        Update
    }
}
